// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVrHBrj0TZ0Sg6cfIoQGBXe3Sx95_sFyM',
    appId: '1:232103282116:web:2ca374ab385d27728bd091',
    messagingSenderId: '232103282116',
    projectId: 'artify-5d355',
    authDomain: 'artify-5d355.firebaseapp.com',
    storageBucket: 'artify-5d355.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDOAM7fhb3KE_P-dcFKvfQ7FmQRd2z358',
    appId: '1:232103282116:android:17aa190a669155898bd091',
    messagingSenderId: '232103282116',
    projectId: 'artify-5d355',
    storageBucket: 'artify-5d355.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2nbcVaF7uPOs9aNkHS7EsU9-y5earGXw',
    appId: '1:232103282116:ios:1becb31310e03cd08bd091',
    messagingSenderId: '232103282116',
    projectId: 'artify-5d355',
    storageBucket: 'artify-5d355.appspot.com',
    iosClientId: '232103282116-o3skfd9rne907cihmu120rq4echjuv0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.artify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2nbcVaF7uPOs9aNkHS7EsU9-y5earGXw',
    appId: '1:232103282116:ios:2f07c796fe439dec8bd091',
    messagingSenderId: '232103282116',
    projectId: 'artify-5d355',
    storageBucket: 'artify-5d355.appspot.com',
    iosClientId: '232103282116-2080podknu3qa1qditc5dojpcukmbie7.apps.googleusercontent.com',
    iosBundleId: 'com.example.artify.RunnerTests',
  );
}
